// Objective-C API for talking to gopointerderefcrash Go package.
//   gobind -lang=objc gopointerderefcrash
//
// File is generated by gobind. Do not edit.

#ifndef __Gopointerderefcrash_H__
#define __Gopointerderefcrash_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class GopointerderefcrashX;

@interface GopointerderefcrashX : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t y;
@end

FOUNDATION_EXPORT void GopointerderefcrashTestDeref(void);

#endif
