
// Objective-C API for talking to the following Go packages
//
//	gopointerderefcrash
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gopointerderefcrash_FRAMEWORK_H__
#define __Gopointerderefcrash_FRAMEWORK_H__

#include "Gopointerderefcrash.objc.h"
#include "Universe.objc.h"

#endif
